---
title: "Assignment4"
author: "yaru peng"
date: "4/13/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##1)
###12.6.1
library(tidyverse)

tidyr::who

who %>%
  gather(code, value, new_sp_m014:newrel_f65, na.rm = TRUE) %>% 
  mutate(code = stringr::str_replace(code, "newrel", "new_rel")) %>%
  separate(code, c("new", "var", "sexage")) %>% 
  select(-new, -iso2, -iso3) %>% 
  separate(sexage, c("sex", "age"), sep = 1)

##problem 3
select(who,country, -iso2, -iso3) %>%
  distinct() %>%
  group_by(country) %>%
  filter(n()>1)

##problem 4
who %>%
  gather(code, value, new_sp_m014:newrel_f65, na.rm = TRUE) %>% 
  mutate(code = stringr::str_replace(code,"newrel","new_rel")) %>%
  separate(code,c("new","type","sexage")) %>% 
  select(-new, -iso2, -iso3) %>% 
  separate(sexage, c("sex","age"), sep=1) %>% 
  group_by(country, year, sex) %>%
  filter(year > 1995) %>%
  summarise(cases = sum(value)) %>%
  unite(country_sex, country, sex, remove = FALSE) %>%
  ggplot(aes(x = year, y = cases, group = country_sex,   
  colour = sex)) + geom_line()

```
#2)
#10.5
#problem 5
  Enframe converts named atomic vectors or lists to two-column data frames. For unnamed vectors, the natural sequence is used as name column.

```{r}
#3)
  pew <- as.tibble(read.csv("pew.csv"))
  pew.tidy <-pew %>%   
  gather(key="Income",value="Frenquency", -religion)
  pew.tidy
```

```{r}
##4)
library(tidyverse)
  bb <- as.tibble(read.csv("billboard.csv"))
  
  bb.tidy <- bb %>% 
     gather(key = "week", value = "rank" , -year, -artist.inverted,-track, -time, -genre,   
            -date.entered, ... = -date.peaked)%>% 
     select(year, artist=artist.inverted, time, track, date=date.entered, week, rank) %>% 
     arrange(track)%>% 
     filter(!is.na(rank))%>% 
     separate(week, into=c("A","B","C"), sep=c(1:2), convert = F)%>% 
     select(-A,-C) %>% 
     dplyr::rename(week = B) %>% 
     arrange(artist,track) %>% 
     mutate(date=as.Date(date) + (as.numeric(week)-1)*7) %>%
     mutate(rank = as.integer(rank))
  bb.tidy
```

